services:
  postgres:
    container_name: expenses-base
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
     - postgres
    restart: unless-stopped

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: